config/routes.rb
Rails.application.routes.draw do
  root 'drops#index'
  resources :drops
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drop.rb
class Drop < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drops_controller.rb
class DropsController < ApplicationController
  before_action :set_drop, only: [:show, :edit, :update, :destroy]

  # GET /drops
  # GET /drops.json
  def index
    @drops = Drop.all
    @drop = Drop.new
  end

  # GET /drops/1
  # GET /drops/1.json
  def show
  end

  # GET /drops/new
  def new
    @drop = Drop.new
  end

  # GET /drops/1/edit
  def edit
  end

  # POST /drops
  # POST /drops.json
  def create
    @drop = Drop.new(drop_params)

    respond_to do |format|
      if @drop.save
        format.html { redirect_to root_path, notice: 'Drop was successfully created.' }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drops/1
  # PATCH/PUT /drops/1.json
  def update
    respond_to do |format|
      if @drop.update(drop_params)
        format.html { redirect_to @drop, notice: 'Drop was successfully updated.' }
        format.json { render :show, status: :ok, location: @drop }
      else
        format.html { render :edit }
        format.json { render json: @drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drops/1
  # DELETE /drops/1.json
  def destroy
    @drop.destroy
    respond_to do |format|
      format.html { redirect_to drops_url, notice: 'Drop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drop
      @drop = Drop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def drop_params
      params.fetch(:drop, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drops_helper.rb
module DropsHelper
end

app/views/drops/_form.html.erb
<%= form_with(model: drop, remote: true) do |form| %>
  <% if drop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(drop.errors.count, "error") %> prohibited this drop from being saved:</h2>

      <ul>
        <% drop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drops/edit.html.erb
<h1>Editing Drop</h1>

<%= render 'form', drop: @drop %>

<%= link_to 'Show', @drop %> |
<%= link_to 'Back', drops_path %>

app/views/drops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drops</h1>
<% @drops.each do |drop| %>
  <%= link_to drop, method: :delete, remote: true do %>
    <div class="water">
    </div>
  <% end %>
<% end %>
 

<h1>New Drop</h1>

<%= render 'form', drop: @drop %>
<script>
  // jGravity works best when targeting the body
  
    $('body').jGravity({ 
      target: 'everything'
    });
</script>

app/views/drops/new.html.erb
<h1>New Drop</h1>

<%= render 'form', drop: @drop %>

<%= link_to 'Back', drops_path %>

app/views/drops/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_drop_path(@drop) %> |
<%= link_to 'Back', drops_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- jQuery *Required -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
            crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'gravity' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>